### ISSUE TITLE
Change repo for purescript-phantom bower registry

### ISSUE THREAD

**Issue by dgendill** [purescripters/purescript-phantom#10]
Hi, @Risto-Stevcev , I just noticed that the purescript-phantom bower registry is pointed to your fork at https://github.com/Risto-Stevcev/purescript-phantom. Would you be able to unregister purescript-phantom and point it to https://github.com/purescripters/purescript-phantom?

```
bower login
...
bower unregister purescript-phantom
bower register purescript-phantom git://github.com/purescripters/purescript-phantom.git
```

**Comment by Risto-Stevcev** [comment]
hey @dgendill 
it should be pointing to the right repo now 😃 
sorry I couldn't code review, I've been busy with other stuff

**Comment by dgendill** [comment]
No problem, I know how it goes :)
